-- Corrects the initial guessed schema against the real
-- information_schema.columns dump from live Supabase. Safe to truncate
-- first: only pre-launch test data exists in these 5 tables so far
-- (Better Auth's users/sessions/accounts tables are untouched).

TRUNCATE TABLE cart_items, wishlist_items, orders, contact_messages, brands
  RESTART IDENTITY CASCADE;

-- brands.id: was modeled as BIGSERIAL (bigint + owned sequence). Live is a
-- plain `integer` with no visible column_default -- almost certainly a
-- Postgres identity column (SuperAdminProfilePage.jsx never supplies an id
-- on create). Unwind the bigserial default/sequence and add identity.
ALTER TABLE brands ALTER COLUMN id DROP DEFAULT;
ALTER TABLE brands ALTER COLUMN id TYPE integer;
DROP SEQUENCE IF EXISTS brands_id_seq;
ALTER TABLE brands ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- brands: missing columns real product forms (ProductEditPage.jsx /
-- SuperAdminProfilePage.jsx) actually use.
ALTER TABLE brands ADD COLUMN tag text;
ALTER TABLE brands ADD COLUMN description text;
ALTER TABLE brands ADD COLUMN year integer;
ALTER TABLE brands ADD COLUMN condition text;
ALTER TABLE brands ADD COLUMN metadata jsonb;

-- brands: times_bought is numeric live, not integer; price is
-- unconstrained numeric, not numeric(10,2); brand/model are nullable live.
ALTER TABLE brands ALTER COLUMN times_bought TYPE numeric USING times_bought::numeric;
ALTER TABLE brands ALTER COLUMN times_bought DROP DEFAULT;
ALTER TABLE brands ALTER COLUMN price TYPE numeric;
ALTER TABLE brands ALTER COLUMN brand DROP NOT NULL;
ALTER TABLE brands ALTER COLUMN model DROP NOT NULL;

-- cart_items: watch_id is plain integer, not bigint; price unconstrained
-- numeric; created_at is genuinely timestamptz; user_id nullable live.
ALTER TABLE cart_items ALTER COLUMN watch_id TYPE integer USING watch_id::integer;
ALTER TABLE cart_items ALTER COLUMN price TYPE numeric;
ALTER TABLE cart_items ALTER COLUMN created_at TYPE timestamptz USING created_at AT TIME ZONE 'UTC';
ALTER TABLE cart_items ALTER COLUMN user_id DROP NOT NULL;

-- wishlist_items: product_id is TEXT, not numeric at all; product_name /
-- product_price are nullable live.
ALTER TABLE wishlist_items ALTER COLUMN product_id TYPE text USING product_id::text;
ALTER TABLE wishlist_items ALTER COLUMN product_name DROP NOT NULL;
ALTER TABLE wishlist_items ALTER COLUMN product_price TYPE numeric;
ALTER TABLE wishlist_items ALTER COLUMN product_price DROP NOT NULL;

-- orders: missing a separate created_at column (distinct from order_date);
-- items needs a '[]' default; shipped_at is genuinely timestamptz;
-- total_amount unconstrained numeric.
ALTER TABLE orders ADD COLUMN created_at timestamp DEFAULT now();
ALTER TABLE orders ALTER COLUMN items SET DEFAULT '[]'::jsonb;
ALTER TABLE orders ALTER COLUMN shipped_at TYPE timestamptz USING shipped_at AT TIME ZONE 'UTC';
ALTER TABLE orders ALTER COLUMN total_amount TYPE numeric;

-- contact_messages: created_at is genuinely timestamptz.
ALTER TABLE contact_messages ALTER COLUMN created_at TYPE timestamptz USING created_at AT TIME ZONE 'UTC';
