-- Hand-written migration (not generated by `prisma migrate dev`), per the
-- plan: Postgres functions are outside Prisma's schema.prisma DDL surface.
--
-- Matches the live Supabase definition exactly (confirmed via
-- `select pg_get_functiondef(oid) from pg_proc where proname = 'increment_times_bought'`):
-- product_id is bigint (brands.id is bigint, not a 32-bit int), plpgsql,
-- SECURITY DEFINER, atomic single UPDATE (safe under concurrent
-- invocations without explicit row locking).
CREATE OR REPLACE FUNCTION public.increment_times_bought(product_id bigint, quantity_to_add integer)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
BEGIN
  UPDATE brands
  SET times_bought = COALESCE(times_bought, 0) + quantity_to_add
  WHERE id = product_id;
END;
$function$;
